name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          sudo curl -sSL "https://github.com/mvdan/sh/releases/download/v3.4.3/shfmt_v3.4.3_linux_amd64" -o /usr/local/bin/shfmt
          sudo chmod +x /usr/local/bin/shfmt

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'

      - name: Run shfmt
        run: shfmt -i 2 -d .

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: [ "20.04", "22.04", "24.04" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.8.2

      - name: Run tests
        run: bats tests
